CREATE USER 'omicron_cms'@'localhost' IDENTIFIED by 'CaSv2QTpR1eafsZr';
CREATE DATABASE IF NOT EXISTS `omicron` DEFAULT CHARACTER SET utf8mb4;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, CREATE TEMPORARY TABLES, EVENT, TRIGGER, SHOW VIEW, EXECUTE ON `omicron`.* TO 'omicron_cms'@'localhost';
